// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.0
// source: bike.proto

package order_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBikeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BikeStatus   string  `protobuf:"bytes,1,opt,name=bike_status,json=bikeStatus,proto3" json:"bike_status,omitempty"`
	BikeNumber   string  `protobuf:"bytes,2,opt,name=bike_number,json=bikeNumber,proto3" json:"bike_number,omitempty"`
	BikeModel    string  `protobuf:"bytes,3,opt,name=bike_model,json=bikeModel,proto3" json:"bike_model,omitempty"`
	StartedPrice float64 `protobuf:"fixed64,4,opt,name=started_price,json=startedPrice,proto3" json:"started_price,omitempty"`
	EndPrice     float64 `protobuf:"fixed64,5,opt,name=end_price,json=endPrice,proto3" json:"end_price,omitempty"`
	Colour       string  `protobuf:"bytes,6,opt,name=colour,proto3" json:"colour,omitempty"`
}

func (x *CreateBikeReq) Reset() {
	*x = CreateBikeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBikeReq) ProtoMessage() {}

func (x *CreateBikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBikeReq.ProtoReflect.Descriptor instead.
func (*CreateBikeReq) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBikeReq) GetBikeStatus() string {
	if x != nil {
		return x.BikeStatus
	}
	return ""
}

func (x *CreateBikeReq) GetBikeNumber() string {
	if x != nil {
		return x.BikeNumber
	}
	return ""
}

func (x *CreateBikeReq) GetBikeModel() string {
	if x != nil {
		return x.BikeModel
	}
	return ""
}

func (x *CreateBikeReq) GetStartedPrice() float64 {
	if x != nil {
		return x.StartedPrice
	}
	return 0
}

func (x *CreateBikeReq) GetEndPrice() float64 {
	if x != nil {
		return x.EndPrice
	}
	return 0
}

func (x *CreateBikeReq) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

type CreateBikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BikeStatus   string  `protobuf:"bytes,1,opt,name=bike_status,json=bikeStatus,proto3" json:"bike_status,omitempty"`
	BikeNumber   string  `protobuf:"bytes,2,opt,name=bike_number,json=bikeNumber,proto3" json:"bike_number,omitempty"`
	BikeModel    string  `protobuf:"bytes,3,opt,name=bike_model,json=bikeModel,proto3" json:"bike_model,omitempty"`
	StartedPrice float64 `protobuf:"fixed64,4,opt,name=started_price,json=startedPrice,proto3" json:"started_price,omitempty"`
	EndPrice     float64 `protobuf:"fixed64,5,opt,name=end_price,json=endPrice,proto3" json:"end_price,omitempty"`
	Colour       string  `protobuf:"bytes,6,opt,name=colour,proto3" json:"colour,omitempty"`
	Id           string  `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt    string  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *CreateBikeResponse) Reset() {
	*x = CreateBikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBikeResponse) ProtoMessage() {}

func (x *CreateBikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBikeResponse.ProtoReflect.Descriptor instead.
func (*CreateBikeResponse) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBikeResponse) GetBikeStatus() string {
	if x != nil {
		return x.BikeStatus
	}
	return ""
}

func (x *CreateBikeResponse) GetBikeNumber() string {
	if x != nil {
		return x.BikeNumber
	}
	return ""
}

func (x *CreateBikeResponse) GetBikeModel() string {
	if x != nil {
		return x.BikeModel
	}
	return ""
}

func (x *CreateBikeResponse) GetStartedPrice() float64 {
	if x != nil {
		return x.StartedPrice
	}
	return 0
}

func (x *CreateBikeResponse) GetEndPrice() float64 {
	if x != nil {
		return x.EndPrice
	}
	return 0
}

func (x *CreateBikeResponse) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

func (x *CreateBikeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateBikeResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateBikeResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BikeId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BikeId) Reset() {
	*x = BikeId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BikeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BikeId) ProtoMessage() {}

func (x *BikeId) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BikeId.ProtoReflect.Descriptor instead.
func (*BikeId) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{2}
}

func (x *BikeId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSingleBikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BikeStatus   string  `protobuf:"bytes,1,opt,name=bike_status,json=bikeStatus,proto3" json:"bike_status,omitempty"`
	BikeNumber   string  `protobuf:"bytes,2,opt,name=bike_number,json=bikeNumber,proto3" json:"bike_number,omitempty"`
	BikeModel    string  `protobuf:"bytes,3,opt,name=bike_model,json=bikeModel,proto3" json:"bike_model,omitempty"`
	StartedPrice float64 `protobuf:"fixed64,4,opt,name=started_price,json=startedPrice,proto3" json:"started_price,omitempty"`
	EndPrice     float64 `protobuf:"fixed64,5,opt,name=end_price,json=endPrice,proto3" json:"end_price,omitempty"`
	Colour       string  `protobuf:"bytes,6,opt,name=colour,proto3" json:"colour,omitempty"`
	Id           string  `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt    string  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *GetSingleBikeResponse) Reset() {
	*x = GetSingleBikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleBikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleBikeResponse) ProtoMessage() {}

func (x *GetSingleBikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleBikeResponse.ProtoReflect.Descriptor instead.
func (*GetSingleBikeResponse) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{3}
}

func (x *GetSingleBikeResponse) GetBikeStatus() string {
	if x != nil {
		return x.BikeStatus
	}
	return ""
}

func (x *GetSingleBikeResponse) GetBikeNumber() string {
	if x != nil {
		return x.BikeNumber
	}
	return ""
}

func (x *GetSingleBikeResponse) GetBikeModel() string {
	if x != nil {
		return x.BikeModel
	}
	return ""
}

func (x *GetSingleBikeResponse) GetStartedPrice() float64 {
	if x != nil {
		return x.StartedPrice
	}
	return 0
}

func (x *GetSingleBikeResponse) GetEndPrice() float64 {
	if x != nil {
		return x.EndPrice
	}
	return 0
}

func (x *GetSingleBikeResponse) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

func (x *GetSingleBikeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSingleBikeResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetSingleBikeResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetListBikesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetListBikesReq) Reset() {
	*x = GetListBikesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListBikesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBikesReq) ProtoMessage() {}

func (x *GetListBikesReq) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBikesReq.ProtoReflect.Descriptor instead.
func (*GetListBikesReq) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{4}
}

func (x *GetListBikesReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListBikesReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetListBikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetBikes []*GetSingleBikeResponse `protobuf:"bytes,1,rep,name=getBikes,proto3" json:"getBikes,omitempty"`
	Count    int32                    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetListBikesResponse) Reset() {
	*x = GetListBikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListBikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBikesResponse) ProtoMessage() {}

func (x *GetListBikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBikesResponse.ProtoReflect.Descriptor instead.
func (*GetListBikesResponse) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{5}
}

func (x *GetListBikesResponse) GetGetBikes() []*GetSingleBikeResponse {
	if x != nil {
		return x.GetBikes
	}
	return nil
}

func (x *GetListBikesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateBikeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BikeStatus   string  `protobuf:"bytes,1,opt,name=bike_status,json=bikeStatus,proto3" json:"bike_status,omitempty"`
	BikeNumber   string  `protobuf:"bytes,2,opt,name=bike_number,json=bikeNumber,proto3" json:"bike_number,omitempty"`
	BikeModel    string  `protobuf:"bytes,3,opt,name=bike_model,json=bikeModel,proto3" json:"bike_model,omitempty"`
	StartedPrice float64 `protobuf:"fixed64,4,opt,name=started_price,json=startedPrice,proto3" json:"started_price,omitempty"`
	EndPrice     float64 `protobuf:"fixed64,5,opt,name=end_price,json=endPrice,proto3" json:"end_price,omitempty"`
	Colour       string  `protobuf:"bytes,6,opt,name=colour,proto3" json:"colour,omitempty"`
	Id           string  `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateBikeReq) Reset() {
	*x = UpdateBikeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBikeReq) ProtoMessage() {}

func (x *UpdateBikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBikeReq.ProtoReflect.Descriptor instead.
func (*UpdateBikeReq) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBikeReq) GetBikeStatus() string {
	if x != nil {
		return x.BikeStatus
	}
	return ""
}

func (x *UpdateBikeReq) GetBikeNumber() string {
	if x != nil {
		return x.BikeNumber
	}
	return ""
}

func (x *UpdateBikeReq) GetBikeModel() string {
	if x != nil {
		return x.BikeModel
	}
	return ""
}

func (x *UpdateBikeReq) GetStartedPrice() float64 {
	if x != nil {
		return x.StartedPrice
	}
	return 0
}

func (x *UpdateBikeReq) GetEndPrice() float64 {
	if x != nil {
		return x.EndPrice
	}
	return 0
}

func (x *UpdateBikeReq) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

func (x *UpdateBikeReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateBikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BikeStatus   string  `protobuf:"bytes,1,opt,name=bike_status,json=bikeStatus,proto3" json:"bike_status,omitempty"`
	BikeNumber   string  `protobuf:"bytes,2,opt,name=bike_number,json=bikeNumber,proto3" json:"bike_number,omitempty"`
	BikeModel    string  `protobuf:"bytes,3,opt,name=bike_model,json=bikeModel,proto3" json:"bike_model,omitempty"`
	StartedPrice float64 `protobuf:"fixed64,4,opt,name=started_price,json=startedPrice,proto3" json:"started_price,omitempty"`
	EndPrice     float64 `protobuf:"fixed64,5,opt,name=end_price,json=endPrice,proto3" json:"end_price,omitempty"`
	Colour       string  `protobuf:"bytes,6,opt,name=colour,proto3" json:"colour,omitempty"`
	Id           string  `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt    string  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *UpdateBikeResponse) Reset() {
	*x = UpdateBikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBikeResponse) ProtoMessage() {}

func (x *UpdateBikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBikeResponse.ProtoReflect.Descriptor instead.
func (*UpdateBikeResponse) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBikeResponse) GetBikeStatus() string {
	if x != nil {
		return x.BikeStatus
	}
	return ""
}

func (x *UpdateBikeResponse) GetBikeNumber() string {
	if x != nil {
		return x.BikeNumber
	}
	return ""
}

func (x *UpdateBikeResponse) GetBikeModel() string {
	if x != nil {
		return x.BikeModel
	}
	return ""
}

func (x *UpdateBikeResponse) GetStartedPrice() float64 {
	if x != nil {
		return x.StartedPrice
	}
	return 0
}

func (x *UpdateBikeResponse) GetEndPrice() float64 {
	if x != nil {
		return x.EndPrice
	}
	return 0
}

func (x *UpdateBikeResponse) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

func (x *UpdateBikeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBikeResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UpdateBikeResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_bike_proto protoreflect.FileDescriptor

var file_bike_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69,
	0x6b, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x62, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62,
	0x69, 0x6b, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x62, 0x69, 0x6b, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x69, 0x6b, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x69, 0x6b, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x22, 0x9d, 0x02, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x62, 0x69, 0x6b, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x62, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x6b, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x6b, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x18, 0x0a, 0x06, 0x42, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xa0, 0x02, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x42, 0x69, 0x6b,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69, 0x6b,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x62, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69,
	0x6b, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x62, 0x69, 0x6b, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x69, 0x6b, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x69, 0x6b, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f,
	0x6c, 0x6f, 0x75, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x3f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x6b,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x22, 0x6e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69,
	0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x08, 0x67,
	0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x08, 0x67, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0xda, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69,
	0x6b, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x6b, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x6b,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x6b, 0x65, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x6b,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x6e, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x65, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f,
	0x75, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x9d, 0x02, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6b, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69, 0x6b, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69,
	0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69, 0x6b, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62,
	0x69, 0x6b, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x6b,
	0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x69, 0x6b, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x6c, 0x6f, 0x75, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f,
	0x75, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x42, 0x18, 0x5a, 0x16, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_bike_proto_rawDescOnce sync.Once
	file_bike_proto_rawDescData = file_bike_proto_rawDesc
)

func file_bike_proto_rawDescGZIP() []byte {
	file_bike_proto_rawDescOnce.Do(func() {
		file_bike_proto_rawDescData = protoimpl.X.CompressGZIP(file_bike_proto_rawDescData)
	})
	return file_bike_proto_rawDescData
}

var file_bike_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bike_proto_goTypes = []interface{}{
	(*CreateBikeReq)(nil),         // 0: order_service.CreateBikeReq
	(*CreateBikeResponse)(nil),    // 1: order_service.CreateBikeResponse
	(*BikeId)(nil),                // 2: order_service.BikeId
	(*GetSingleBikeResponse)(nil), // 3: order_service.GetSingleBikeResponse
	(*GetListBikesReq)(nil),       // 4: order_service.GetListBikesReq
	(*GetListBikesResponse)(nil),  // 5: order_service.GetListBikesResponse
	(*UpdateBikeReq)(nil),         // 6: order_service.UpdateBikeReq
	(*UpdateBikeResponse)(nil),    // 7: order_service.UpdateBikeResponse
}
var file_bike_proto_depIdxs = []int32{
	3, // 0: order_service.GetListBikesResponse.getBikes:type_name -> order_service.GetSingleBikeResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bike_proto_init() }
func file_bike_proto_init() {
	if File_bike_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bike_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBikeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BikeId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleBikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListBikesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListBikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBikeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bike_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bike_proto_goTypes,
		DependencyIndexes: file_bike_proto_depIdxs,
		MessageInfos:      file_bike_proto_msgTypes,
	}.Build()
	File_bike_proto = out.File
	file_bike_proto_rawDesc = nil
	file_bike_proto_goTypes = nil
	file_bike_proto_depIdxs = nil
}
